### ISSUE TITLE
expand the bounding box slightly.

### ISSUE THREAD

**Issue by bw4sz** [weecology/EvergladesSpeciesModel#18]
If we can add a small buffer before we crop the species class boxes, we can recover any cut-off birds.

**Comment by ethanwhite** [comment]
@skmorgane & I visualized ~20 images and a bunch of different additional buffers and we think that moving from the current 50x50 to 60x60 represents a reasonable compromise between making the boxes big enough to typically include all of the large birds while introducing too much additional overlap between nearby WHIB's.

**Comment by ethanwhite** [comment]
That said, there are still definitely cases where this isn't big enough to capture entire large birds, e.g., the GREG in this example ![Screenshot from 2021-11-30 11-41-29](https://user-images.githubusercontent.com/744427/144089668-261fe3e9-7260-4458-ab89-1c8113b05221.png)

**Comment by ethanwhite** [comment]
Increase bounding box size from 50x50 to 60x60 or 70x70 doesn't appear to have any significant impact. Decreasing it to 20x20 does negatively impact performance (confirming that we're actually doing something with the changes).

There are tradeoffs between smaller and larger species, so one option might be different box buffers depending on the species (or ultimately, bounding box labels instead of point labels).

**Comment by ethanwhite** [comment]
Doing one more run at 100x100 and then probably calling this good.

**Comment by ethanwhite** [comment]
No improvement in any of these experiments.
